include:
- file: scenario://workspace/datagen/include/target/sim_scenarios/include/extra_data_noise_config.inc.yaml
extra_data:
   uc_config_path: "sim_config/uc_config_default.yaml"
   sync_mode: "sim_clock"
   plugins: "simulation/resources/sim_scenarios/include/python_box/targetx86.inc.yaml"
   enable_noise: "false"
integration_options:
  actor_reporting_version:
    minor: 1
