extra_data:
   uc_config_path: "sim_config/uc_config_mot_perfect.yaml"
   sync_mode: "sim_clock"
   pb_recorder: ""
   noise_config: "sim_config/noise_config/noise_config_default.json"
   enable_noise: "true"
