spectral:
  enable: true
  label_requests:
  - request_name: semantic_images
    semantic_image: {}
  - request_name: actor_2d
    bounding_box_2d:
      object_type: ALL_ACTORS
  - request_name: traffic_sign_2d
    bounding_box_2d:
      object_type: TRAFFIC_SIGN_FACES
  - request_name: actor_3d
    bounding_box_3d:
      object_type: ALL_ACTORS
  - request_name: traffic_sign_3d
    bounding_box_3d:
      object_type: TRAFFIC_SIGN_FACES
  
  use_spectral_instance: true
  spectral_instances:
  - name: spectral-instance-0
    gpu_device_id: 0
    sensor_names:
      - camera_g1_8mb_image_narrow_front_ws
  - name: spectral-instance-1
    gpu_device_id: 1
    sensor_names:
      - camera_g1_8mb_image_extwide_front_ws

vehicle:
  sensors:
    sensor_models:
    - camera_model:
#        fidelity:
#          super_sampling: 2.0
        format:
          data: ROS_TOPIC
        library:
          model: generic
          vendor: applied
        mount:
          px: 1.9671563176463
          py: -0.10508203694231931
          pz: 1.449129435472988
          quaternion:
            qw: 0.9999729608349087
            qx: 0.0014560899872085075
            qy: 0.002308262540907462
            qz: 0.006828566837743851
        name: camera_g1_8mb_image_extwide_front_ws
        standard_params:
          field_of_view:
            az: 1.733425103990766
            el: 0.7627504272014397
          rendered_field_of_view: 2.154
          frame_rate: 2
          lens_params:
            center_position:
              x: 0.0013522554485555505
              y: -0.2859837110481587
          sensor_params:
            resolution:
              x: 3946
              y: 1412
            type: VISIBLE
    - camera_model:
        format:
          data: ROS_TOPIC
        library:
          model: generic
          vendor: applied
        mount:
          px: 2.2583135388682463
          py: -0.0818153690988163
          pz: 1.4649917022423473
          quaternion:
            qw: 0.9998757422122109
            qx: 0.0049235293295927535
            qy: 0.01418551998166609
            qz: -0.004798960030113791
        name: camera_g1_8mb_image_narrow_front_ws
        standard_params:
          rendered_field_of_view: 0.5398811282264511
          field_of_view:
            az: 0.4882437467053002
            el: 0.24398756157524507
          frame_rate: 2
          lens_params:
            center_position:
              x: 0.026933333333333365
              y: -0.05416164241164245
          sensor_params:
            resolution:
              x: 3900
              y: 1924
            type: VISIBLE
